server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    keyId: LTAI5tPoFszjcAYVhNPyWEAx
    keySecret: motQUGGsTDJ1IbuqLw35xfsmkK1vQe
    bucketName: srb-file-220914